### ISSUE TITLE
.env file missing

### ISSUE THREAD

**Issue by zaaakher** [thomasmost/bot_auther#1]
I get this error when I try npm start for the first time 

```

 throw Error(
        ^
Error: Missing required configuration; did you remember to add your .env file?
    at Object.<anonymous> (X:\Sikka\Apps\bot-author\app.ts:15:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (X:\Sikka\Apps\bot-author\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (X:\Sikka\Apps\bot-author\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at main (X:\Sikka\Apps\bot-author\node_modules\ts-node\src\bin.ts:225:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bot_auther@1.0.0 start: `ts-node app.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bot_auther@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zakher\AppData\Roaming\npm-cache\_logs\2020-12-02T05_40_55_893Z-debug.log

```

When I first cloned the repo I did `npm install` and then `npm start` but still doesn't work.

**Comment by thomasmost** [comment]
I believe you're missing step 2 from [Instance Setup](https://github.com/thomasmost/bot_auther#instance-setup)

> Now add an .env file in the repository and fill in your application consumer keys like so:
> TWITTER_APP_CONSUMER_KEY=your_key_here
> TWITTER_APP_CONSUMER_SECRET=your_secret_here

**Comment by thomasmost** [comment]
Hm, the way I broke up these setup steps is confusing. I'll make some adjustments 🙂

**Comment by thomasmost** [comment]
I've updated the README to be clearer. I'm closing this for now but let me know if you need additional support!
